### Obtener peliculas
http://localhost:3000/movies

### Obtener pelicula por id
http://localhost:3000/movies/1

### añadir pelicula
POST http://localhost:3000/movies/add
Content-Type: application/json

{
  "nombre": "Volver al futuro",
  "estreno": 1985,
  "descripcion": "Una máquina del tiempo transporta a un adolescente a los años 50, cuando sus padres todavía estudiaban en la secundaria."
}


### eliminar pelicula
DELETE http://localhost:3000/movies/d768e0f0-cf1b-420f-9ae3-94b955de701b